# Generated by Django 4.0.1 on 2022-04-23 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog_app', '0002_alter_activity_options_alter_jiujitsu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
