# Generated by Django 4.0.1 on 2022-04-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jlog_app', '0005_alter_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthTraining',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jlog_app.activity')),
            ],
            options={
                'verbose_name': 'Strength Training',
                'verbose_name_plural': 'Strength Trainings',
            },
            bases=('jlog_app.activity',),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('strength_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='jlog_app.strengthtraining')),
            ],
        ),
    ]
