# Generated by Django 4.0.1 on 2022-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog_app', '0006_strengthtraining_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
